export const PRODUCTS_SEED = [
  {
    category: 'Breads',
    name: 'Artisan Sourdough',
    description: 'Naturally leavened, crackling crust, open airy crumb.',
    price: 8.5,
    featured: true,
    bestSeller: true,
    seasonal: false,
    dietary: ['Vegan'],
    allergen: 'Gluten',
    available: true,
  },
  {
    category: 'Breads',
    name: 'Rustic Baguette',
    description: 'Crisp crust with a soft, chewy center.',
    price: 5.5,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: ['Vegan'],
    allergen: 'Gluten',
    available: true,
  },
  {
    category: 'Breads',
    name: 'Honey Wheat Loaf',
    description: 'Wholesome wheat sweetened with local honey.',
    price: 7,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten',
    available: true,
  },
  {
    category: 'Breads',
    name: 'Olive Rosemary Loaf',
    description: 'Kalamata olives and fresh rosemary folded through.',
    price: 8,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: ['Vegan'],
    allergen: 'Gluten',
    available: true,
  },
  {
    category: 'Cakes',
    name: 'Chocolate Fudge Cake',
    description: 'Rich layers of dark chocolate and silky ganache.',
    price: 42,
    featured: true,
    bestSeller: true,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Cakes',
    name: 'Lemon Elderflower Cake',
    description: 'Bright citrus sponge with elderflower cream.',
    price: 44,
    featured: false,
    bestSeller: false,
    seasonal: true,
    dietary: [],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Cakes',
    name: 'Carrot Walnut Cake',
    description: 'Warm spice, toasted walnut, cream cheese frosting.',
    price: 40,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Eggs, Nuts',
    available: true,
  },
  {
    category: 'Cakes',
    name: 'Vanilla Bean Layer Cake',
    description: 'Classic vanilla bean sponge, silky buttercream.',
    price: 38,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Pastries',
    name: 'Butter Croissant',
    description: 'Flaky, golden, and buttery with delicate layers.',
    price: 4.5,
    featured: true,
    bestSeller: true,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy',
    available: true,
  },
  {
    category: 'Pastries',
    name: 'Almond Croissant',
    description: 'Twice-baked and filled with almond cream.',
    price: 5.5,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Nuts',
    available: true,
  },
  {
    category: 'Pastries',
    name: 'Pain au Chocolat',
    description: 'Buttery layers wrapped around dark chocolate.',
    price: 5,
    featured: false,
    bestSeller: true,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy',
    available: true,
  },
  {
    category: 'Pastries',
    name: 'Cinnamon Roll',
    description: 'Soft, swirled, and finished with cream cheese icing.',
    price: 5.5,
    featured: true,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Cookies',
    name: 'Sea Salt Chocolate Chip',
    description: 'Crisp edges, gooey center, flaky sea salt.',
    price: 3.5,
    featured: false,
    bestSeller: true,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Cookies',
    name: 'Oatmeal Raisin',
    description: 'Chewy oats, plump raisins, warm cinnamon.',
    price: 3.25,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Cookies',
    name: 'Almond Shortbread',
    description: 'Buttery and delicate with toasted almond.',
    price: 3.5,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy, Nuts',
    available: true,
  },
  {
    category: 'Cookies',
    name: 'Double Ginger Molasses',
    description: 'Spiced with crystallized and ground ginger.',
    price: 3.25,
    featured: false,
    bestSeller: false,
    seasonal: true,
    dietary: ['Vegan'],
    allergen: 'Gluten',
    available: true,
  },
  {
    category: 'Breakfast',
    name: 'Ham & Gruyère Croissant',
    description: 'Savory croissant layered with ham and melted gruyère.',
    price: 7.5,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: [],
    allergen: 'Gluten, Dairy',
    available: true,
  },
  {
    category: 'Breakfast',
    name: 'Everything Bagel',
    description: 'Hand-rolled and topped with our everything blend.',
    price: 4,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: ['Vegan'],
    allergen: 'Gluten',
    available: true,
  },
  {
    category: 'Breakfast',
    name: 'Berry Yogurt Parfait',
    description: 'Layered yogurt, seasonal berries, house granola.',
    price: 6.5,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: ['Vegetarian', 'GF option'],
    allergen: 'Dairy',
    available: true,
  },
  {
    category: 'Breakfast',
    name: 'Spinach & Feta Quiche',
    description: 'Flaky crust filled with spinach, feta, and egg.',
    price: 7,
    featured: false,
    bestSeller: false,
    seasonal: false,
    dietary: ['Vegetarian'],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Seasonal',
    name: 'Pumpkin Spice Loaf',
    description: 'Warm spice loaf topped with cinnamon streusel.',
    price: 8,
    featured: false,
    bestSeller: false,
    seasonal: true,
    dietary: ['Vegetarian'],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Seasonal',
    name: 'Key Lime Tart',
    description: 'Florida key lime curd in a buttery shortbread shell.',
    price: 6,
    featured: false,
    bestSeller: false,
    seasonal: true,
    dietary: ['Vegetarian'],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
  {
    category: 'Seasonal',
    name: 'Peach Galette',
    description: 'Rustic free-form tart with local summer peaches.',
    price: 7,
    featured: false,
    bestSeller: false,
    seasonal: true,
    dietary: ['Vegan'],
    allergen: 'Gluten',
    available: true,
  },
  {
    category: 'Seasonal',
    name: 'Gingerbread Cookies',
    description: 'Hand-iced and spiced for the holidays.',
    price: 3.5,
    featured: false,
    bestSeller: false,
    seasonal: true,
    dietary: ['Vegetarian'],
    allergen: 'Gluten, Dairy, Eggs',
    available: true,
  },
];

export const TESTIMONIALS_SEED = [
  {
    quote:
      'The sourdough is unlike anything else in St. Pete — crackling crust, perfect chew. We buy a loaf every weekend.',
    name: 'Rachel M.',
    rating: 5,
  },
  {
    quote:
      'Ordered a custom cake for my daughter’s birthday and it was even better than the photos we sent.',
    name: 'James T.',
    rating: 5,
  },
  {
    quote:
      'Cozy, welcoming, and the croissants are the real deal. This is our Sunday morning ritual now.',
    name: 'Priya S.',
    rating: 5,
  },
];

export const GALLERY_SEED = [
  { category: 'Products', caption: 'Butter croissants, fresh from the oven' },
  { category: 'Bakery', caption: 'Our storefront on Central Avenue' },
  { category: 'Cakes', caption: 'Custom three-tier wedding cake' },
  { category: 'Behind the Scenes', caption: 'Shaping the morning sourdough' },
  { category: 'Pastries', caption: 'Almond croissants cooling on the rack' },
  { category: 'Products', caption: 'Seasonal fruit tarts' },
  { category: 'Bakery', caption: 'Our warm, sunlit dining corner' },
  { category: 'Cakes', caption: 'Chocolate fudge layer cake' },
  { category: 'Behind the Scenes', caption: 'Early morning dough prep' },
  { category: 'Pastries', caption: 'Cinnamon rolls glazed and ready' },
  { category: 'Products', caption: 'Fresh loaves lined up for the case' },
  { category: 'Bakery', caption: 'Golden hour at the counter' },
];
